# Foxix Terminal Configuration
# ~/.config/foxix/foxix.conf

# ── Fuente ─────────────────────────────────────────────────
font_family             JetBrains Mono Nerd Font
font_size               12
bold_font               auto
bold_is_bright          no

# ── Cursor ─────────────────────────────────────────────────
cursor_shape            beam
cursor_beam_thickness   1.5
cursor_blink_interval   0.5

# ── Ventana ────────────────────────────────────────────────
background_opacity      0.78
window_padding_width    25

# ── Shell ──────────────────────────────────────────────────
shell                   fish

# ── Historial ──────────────────────────────────────────────
scrollback_lines        10000
